name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
    job1:
      run:
        shell: bash
        run: /usr/bin/touch build_success
        working-directory: ${{runner.workspace}}/build



