name: my_first_workflow

on:
  push:
    branches: [ master ]


jobs:
  test_push:
    runs-on: [self-hosted, linux]
    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
      - run: wall "privet world"
        working-directory: ${{runner.workspace}}/build
        shell: bash


