name: my_first_workflow_

on:
  push:
    branches: [ master ]
jobs:
  test_push:
    runs-on: [self-hosted, linux]
    steps:
    - name: wall_privet_mir
      run: /usr/bin/wall "privet world" 
      working-directory: ${{runner.workspace}}/build
      shell: bash


